### ISSUE TITLE
Modernising C/C++ Code

### ISSUE THREAD

**Issue by SoapZA** [cbg-ethz/shorah#26]
The current code base emits warnings such as:
```
../../src/shorah/dpm_sampler.cpp:2070:11: warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]
  if (1.0*fabs(running_sum - (n*HISTORY))/(n*HISTORY) > 0.001){
          ^
../../src/shorah/dpm_sampler.cpp:2070:11: note: remove the call to 'fabs' since unsigned values cannot be negative
  if (1.0*fabs(running_sum - (n*HISTORY))/(n*HISTORY) > 0.001){
          ^~~~
../../src/shorah/contain.cpp:76:14: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                if ((r.pos < 0)) {
                     ~~~~~ ^ ~
../../src/shorah/freqEst.cpp:91:14: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
                if ((r.pos < 0)) {
```
I think we should fix these for the next release.

1. The first two are likely due to the C minefield of converting integers of the same rank to an unsigned type, which can likely be resolved by adding a bunch of `static_cast<int>`'s.
2. The second bunch of errors could be deeper, and will likely require converting genomic offsets to signed integers (which is imo better anyways).

**Comment by ozagordi** [comment]
It might be even simpler than that.

The first `fabs` appear in a check that can probably be rewritten or even deleted (it looks pleonastic to me now, but I'm not sure).

The other warnings appear in the global reconstruction part that we might decide to drop.

**Comment by ozagordi** [comment]
If we drop the global reconstruction (after conda-packaging?), the other two warnings will disappear.
