### ISSUE TITLE
Issues with example amplicon_test

### ISSUE THREAD

**Issue by krepsen** [cbg-ethz/shorah#28]
With aid from more competent personnel I've installed the latest shorah release.
Tried the example files to no avail (also unsuccessfully tried with my dataset).
Hope you can identify the problem.

Here's the run/error messages:

```
ngs2@ngs2 ~/Downloads/shorah-1.0.0/examples/amplicon_test $ shorah.py -b ampli_sorted.bam -f reference.fasta
Traceback (most recent call last):
  File "/usr/local/bin/shorah.py", line 142, in <module>
    keep_files=options.k, alpha=options.a)
  File "/home/ngs2/Downloads/shorah-1.0.0/src/python/shorah_dec.py", line 345, in main
    r = aligned_reads.keys()[0]
IndexError: list index out of range
```

**Comment by ozagordi** [comment]
Hi,
thanks for your interest in shorah.
The folder `amplicon_test` contains a test for the program `amplian.py`: local analysis in amplicon mode. You ran `shorah.py`, the wrapper for global analysis.
It's far from perfect, but the [documentation](http://cbg-ethz.github.io/shorah/) also includes some figures to explain the difference. Please consider that global analysis in shorah is now surpassed by other tools like quasirecomb and haploclique (to name a few) and will most likely be ditched in the next release. You can see similar discussions in other issues like #27.

I will close this for now, please open a new issue if you have further questions.

Best.
    Osvaldo
