### ISSUE TITLE
shorah.py fails if there is a . in the FASTA header name

### ISSUE THREAD

**Issue by nickloman** [cbg-ethz/shorah#32]
shorah.py -b alignments/NC_001802.1/illumina/26-A.sorted.bam -f refs/NC_001802.1.fasta -r "NC_001802.1:1768-3000"
Traceback (most recent call last):
  File "shorah/bin/shorah.py", line 139, in <module>
    alpha=args.a, keep_files=args.k, seed=args.S)
  File "shorah/local/lib/python2.7/site-packages/shorah_dec.py", line 438, in main
    beg = int(parts[-2])
ValueError: invalid literal for int() with base 10: 'w'

coverage.txt looks like:

w-NC_001802.1-1768-1968.reads.fas	NC_001802.1	1768	1968	395
w-NC_001802.1-1835-2035.reads.fas	NC_001802.1	1835	2035	691
w-NC_001802.1-1902-2102.reads.fas	NC_001802.1	1902	2102	1703
w-NC_001802.1-1969-2169.reads.fas	NC_001802.1	1969	2169	2200
w-NC_001802.1-2036-2236.reads.fas	NC_001802.1	2036	2236	1705
w-NC_001802.1-2103-2303.reads.fas	NC_001802.1	2103	2303	2405
w-NC_001802.1-2170-2370.reads.fas	NC_001802.1	2170	2370	2128
w-NC_001802.1-2237-2437.reads.fas	NC_001802.1	2237	2437	2512

This is due to the split() on the . character

Suggest instead removing'.reads.fas' from line end

Best
Nick

**Comment by ozagordi** [comment]
Hi @nickloman.
Thanks for spotting this. Yes, definitely somethig we have to correct.

**Comment by woodford87** [comment]
Hi Nick, 

I've got a similar error message from one of my runs. 

`Traceback (most recent call last):
  File "./shorah.py", line 139, in <module>
    alpha=args.a, keep_files=args.k, seed=args.S)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_dec.py", line 438, in main
    beg = int(parts[-2])
ValueError: invalid literal for int() with base 10: 'gb'`

Do you know a way around this problem?

Thanks

**Comment by opplatek** [comment]
The issue with "." in the fasta name is still there (v1.1.3, installed on Feb 26).

**Comment by SoapZA** [comment]
@DrYak this should generally be an easy fix, doable in at most 3-4 days

**Comment by DrYak** [comment]
Fixed in commit 6925abb986e0c796909915122f0bede6ecf8756e
