### ISSUE TITLE
Error running Shorah.py 

### ISSUE THREAD

**Issue by woodford87** [cbg-ethz/shorah#34]
Hi there, 

I'm processing a set of nanopore reads using ShoRAH, the reads are ~2KB in length. 
The script had processed the first batch of reads through dec.py, but then failed when it moved to the second set. I got the following error message when trying to run the shorah.py script. 

`File "./shorah.py", line 139, in <module>
    alpha=args.a, keep_files=args.k, seed=args.S)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_dec.py", line 447, in main
    proposed[beg] = (get_prop(dbg_file), j)
  File "/Users/lukewoodford/shorah/lib/python3.6/site-packages/shorah_dec.py", line 259, in get_prop
    return prop
UnboundLocalError: local variable 'prop' referenced before assignment`

Does anyone know what has caused this error? I chose to run the reads in 3 window shifts of 600bp each, but I could try running it in 1 if this would fix this issue.

**Comment by sposadac** [comment]
I expect the problem is related with low coverage in one of the windows.

**Comment by woodford87** [comment]
Hi, thanks for replying. 

What's the threshold for 'low coverage'?

**Comment by ozagordi** [comment]
I can't give a precise number. Other users have observed a similar behaviour when there is a marked drop in the coverage (this is as precise as "low threshold", I know). For these cases, we always remind that global reconstruction is a very hard problem, and we usually recommend sticking to the local reconstruction.

**Comment by woodford87** [comment]
Thanks Osvaldo, I'll bear that in mind with this analysis.
