### ISSUE TITLE
IndexError: list index out of range when running amplian.py

### ISSUE THREAD

**Issue by nickjhathaway** [cbg-ethz/shorah#36]
When running amplian.py I get the following error and I'm not sure what is causing it. 

```
Traceback (most recent call last):
  File "/data/home/hathawan/shorah-install/bin/amplian.py", line 429, in <module>
    args.s, args.region, args.diversity)
  File "/data/home/hathawan/shorah-install/bin/amplian.py", line 344, in main
    h = list(open('coverage.txt'))[0]
IndexError: list index out of range
```

I'm running the following command

```
amplian.py -b EBNA3cN1MIDJijoye-d1-EBV-1.sorted.bam -f renamed_NC_007605.1.fasta
```

And I have put all my files including output from amplian.py here, http://bib8.umassmed.edu/~hathawan/shorah/

Any help would be appreciated, thanks!

Nick

**Comment by ozagordi** [comment]
Hi Nick.

Try to specify the region. I noticed in your bam file that you only have coverage at the very end of the reference. I managed to start it with this command line (replace with your file name)

    amplian.py -b EBNA3cN1MIDJijoye-d1-EBV-1.sorted.bam -r ebv0:86264-86674 -f your_reference.fasta

Please keep in mind that the different modes are described in [this page](http://cbg-ethz.github.io/shorah/local.html).

Best.
    Osvaldo

**Comment by nickjhathaway** [comment]
Apologies, I had read the part of the local mode finding the area with the highest diversity and I thought it would take into account only regions that had coverage. Since I only have one region I thought it would find this automatically. 

-Nick

**Comment by nickjhathaway** [comment]
Sorry quick question, is the region supplied 1-based or 0-based?

Nick

**Comment by ozagordi** [comment]
Discovery mode must be triggered with the appropriate flag. Barring mistakes, we follow samtools convention for region specification.
