### ISSUE TITLE
Shorah throwing error for PacBio bam files

### ISSUE THREAD

**Issue by zusman** [cbg-ethz/shorah#39]
Hi, 
I have already used shorah for Illumina analysis, But for Pacbio bam file it is throwing this Error:

$ ~/Apps/shorah/shorah.py -b ~/Desktop/noro/file.2-2.consensusreadset_aligned.bam -f ~/Desktop/noro/EU078417_NG12372.fasta
/home/Apps/shorah/diri_sampler/home/Apps/shorah/diri_sampler: : error while loading shared librarieserror while loading shared libraries: : libgsl.so.0libgsl.so.0: : cannot open shared object filecannot open shared object file: : No such file or directoryNo such file or directory

Can you please help me, what possibly be going wrong??
Best Zusman

**Comment by ozagordi** [comment]
Hi @zusman, and my apologies for replying so late. Did you solve this issue? It doesn't seem related to Pacbio, but rather to your system. I would suggest searching the web for "error while loading shared libraries" first.

**Comment by zusman** [comment]
Dear Zargordi, 

I dint seem to fix the issue. I had to provide the results urgently so I used other means. But I would like to know if Shorah works fine for pacbio reads. 
Can you suggest what input parameters are required by shorah when running PacBio platform ccs reads??

Best
Zainab

**Comment by ozagordi** [comment]
I don't have a direct experience with Pacbio reads, so I'm not sure I can say anything really useful. Usual suggestions would apply:
- check whether you are in shotgun mode or amplicon mode (see docs);
- use a window length slightly shorter than typical read length;
- ask yourself if global reconstruction is really needed, use other tools if this is the case.

I'm closing this now.
