### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by opplatek** [cbg-ethz/shorah#44]
During 2 out of 96 calculations I ran into an error `RuntimeError: maximum recursion depth exceeded in cmp`. 

I am not a Python expert so I cannot suggest the best fix. Only what I found on Biostars (https://stackoverflow.com/questions/25105541/python-quicksort-runtime-error-maximum-recursion-depth-exceeded-in-cmp). 

Adding lines
`import sys`
`sys.setrecursionlimit(1500)` (default value should be 1000)
to `shorah_mm.py` fixed the issue but it is definitely not recommended nor optimal.

I am atttaching a shorah log from this failed calculation.

[27_S27_bwamem.filtered.sorted.grp.indelRealigned.duplRem.recal.shorah.txt](https://github.com/cbg-ethz/shorah/files/1863249/27_S27_bwamem.filtered.sorted.grp.indelRealigned.duplRem.recal.shorah.txt)

Best, 
Jan

**Comment by ozagordi** [comment]
Hi Jan,
thanks for your report. I don't want to seem harsh, but I must say that we plan to drop global reconstruction from shorah soon. Time has shown that, for this difficult problem, better alternatives exist. People tend to use shorah in unfavourable situations (low diversity spread over regions way longer than the reads), while its strength should be a sensitive detection of low frequency haplotypes in _local mode_. I will add wontfix label and close it, unless we find other reasons to reopen it.

But thanks again for your interest.
    Osvaldo
