### ISSUE TITLE
latest version no configure file

### ISSUE THREAD

**Issue by dcastaneda5** [cbg-ethz/shorah#65]
Hi,
I was trying to install the latest version where you guys debugged the 'prop' error (which is what I was getting before with earlier versions). However, after I download the tar ball of the new release, I can't see a config file like the other tarballs. After realizing this I ran `autoconf`, and then it generated the `configure` file. When I ran the command posted in your readme.md, `./configure --prefix=/usr/local/shorah/ PYTHON=/usr/local/shorah/bin/python3.6` it gave me the following output:
```
checking whether configure should try to set CXXFLAGS/CPPFLAGS/LDFLAGS... yes
./configure: line 1860: AX_CHECK_ENABLE_DEBUG: command not found
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

I am relatively new to programming, so I am kind of lost here... I am not sure where to find the install.sh to keep going. Thanks in advance,

**Comment by dcastaneda5** [comment]
Hi,
It is working now. The executables are in the virtual environment I created. I will be running my data to see if it works fine now. Thanks a lot!

**Comment by dcastaneda5** [comment]
Hi again,

So I tried running my data in my virtual environment /usr/local/shorah/bin , and whenever I try the following command:

`sudo ./shorah shotgun -b sample1_sorted.bam -f msp1.fasta`

I get the following output from it:

`Executable fil not found, compile first.`

This also happens when I run sudo ./shorah amplicon. However, when I run just sudo ./shorah , I get this, as if it was properly compiled and working:
`
usage: shorah <subcommand> [options]

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit

sub-commands:
  {shotgun,amplicon,snv}
                        available sub-commands
    shotgun             run local analysis in shotgun mode
    amplicon            run local analysis in amplicon mode
    snv                 run single-nucleotide-variant calling

Run `shorah subcommand -h` for more help`

**Comment by DrYak** [comment]
Two different things:

### Privileges

running shorah does not require any root privileges. You do not need to use `sudo` to run it.

### Paths

The fact that you need to explicitely specify `./` makes me think you probably don't have `/usr/local/shorah/bin` in your path (`echo $PATH` to check).

You can add this directory to the path by typing `export PATH="/usr/local/shorah/bin:${PATH}"`. This will add it to the path where executables are searched for.

 - Thus you can then only type `shorah` to run it.
 - Shorah in turn will be able to find its submodules (such as `fil`, `b2w` and `diri_sampler`).

The same is also needed for the python module. If you get errors about python modules not being found, it means your need to set a `PYTHONPATH`. You need to type `export PYTHONPATH="/usr/local/shorah/lib/python`*{ver}*`/site-packages` where *{ver}* == the version of python that you used. e.g.:   `export PYTHONPATH="/usr/local/shorah/lib/python3.7/site-packages` (Just check the content of the directory: `ls /usr/local/shorah/lib/` or use the [TAB] key on your keybaord to auto-complete.).

**Comment by dcastaneda5** [comment]
Yes! This fixed it! Thanks a lot for the insight, now my data is running fine.
