### ISSUE TITLE
Error in vars()

### ISSUE THREAD

**Issue by homopolymer** [cbg-ethz/shorah#7]
I ran snv.py in my data, but got the following error information.  How to resolve it?

Traceback (most recent call last):
  File "/tool/shorah/snv.py", line 440, in <module>
    main(_args, *_vars(opts))
TypeError: vars() argument must have **dict** attribute

**Comment by ibseq** [comment]
Hi Osvaldo, 
catching up with issue above, with my command : shorah snv -b test_sorted.bam -f ~/ref/MN908947.3.fasta -of vcf

I'm getting Coverage file generated by b2w not found.

Any advice?
Also, how can we run shorah on multiple bam files simultaneously ? I have tried vpipe as well but for some reason the vcf file was empty!

thanks!
ibseq
